apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgcxt
  template:
    metadata:
      labels:
        app: cgcxt
    spec:
      containers:
      - image: okteto.dev/cgcxt:latest
        name: cgcxt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e8f25a7c-318a-4b78-9099-dda5fcbe8113"
        - name: Vless_Path
          value: "/xzdgerh"
        - name: Vmess_UUID
          value: "e7f23ca4-4c33-4984-994d-ea0104047bbf"
        - name: Vmess_Path
          value: "/vmdsgwrdg46"
        - name: Share_Path
          value: "/v2link"
